### ISSUE TITLE
[Q] I am not sure whether i am getting started correctly on feature 2

### ISSUE THREAD

**Issue by jorhden** [ADES-FSP/2122s1-CA1#3]
| field | value | example|
| - | - | - |
| Name | Jorden Hang | Jeremiah Ang (As in MS Teams) |
| Class | 2B/24 | 2B/21 |

> Replace `????` with your name and class

**Describe the bug/question/problem you faced**

The first todo step for feature 2 in CA1 brief is to 
1. Add a new API GET /queue to query for the entities currently in queue. See Currently in Queue API.
I have tried to get started on feature 2 based on this but i have some doubts whether my method is correct, moreover im not sure how to continue from here to link it to getting waiting times and such

GET/queue 
![image](https://user-images.githubusercontent.com/82923619/118826489-1e005e80-b8ee-11eb-81c4-8a2278bf72f4.png)

queue_manager.js
![image](https://user-images.githubusercontent.com/82923619/118826671-438d6800-b8ee-11eb-8dad-746a3707aa6e.png)

db_manager.js
![image](https://user-images.githubusercontent.com/82923619/118826698-4ab47600-b8ee-11eb-9149-2186ee4d5a1a.png)

http test
![image](https://user-images.githubusercontent.com/82923619/118826797-5e5fdc80-b8ee-11eb-8a45-4fb08f89d338.png)

can retrieve enqueued customers but after dequeueing, the customers and their arrival timestamps still remain if you send request for the GET/ queue query again
![image](https://user-images.githubusercontent.com/82923619/118826853-6a4b9e80-b8ee-11eb-9393-fb71b27ec81c.png)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Some screenshots you may want to add:
1. All the information about the HTTP request you’re making (e.g. the method, the path, the query, the body, etc…)
2. The response you are getting from the backend.
    1. For website: go to Inspect > Network > Click on request > Response.
3. Your init.sql
4. The complete error message you received

**Additional context**
Add any other context about the problem here. (e.g. using elephantSql instead of Docker)

**Comment by jeremiah-ang** [comment]
The response body you're producing is different from the expected response body as stated in the API document. Otherwise, you're on the right track.
