### ISSUE TITLE
Feature 9 Non-functional requirements

### ISSUE THREAD

**Issue by Azzahabie** [ADES-FSP/2122s1-CA1#6]
### Which requirement are you unsure of? 

![image](https://user-images.githubusercontent.com/69105293/119463072-f852d980-bd73-11eb-83ff-97bc3422e7aa.png)

### What do you understand about it? What do you not understand?

For 2. What does last drop zone mean. Is it when i drag chart A while the chart is being dragged. the previous position of chart A has to be highlighted/ change background color to show that was chart A original position?

For 3. If i were to drag chart A over chart B. Is chart A swapping position with B. OR . chart A z index is greater than B thus overlapping chart B?

Thanks

**Comment by jeremiah-ang** [comment]
The last drop zone is so that I can drop a chart as the last chart. 

Chart A is dropped INFRONT of chart B
