### ISSUE TITLE
Feature 6 ( non functional requirement 2 and 3 )

### ISSUE THREAD

**Issue by shoban213** [ADES-FSP/2122s1-CA1#7]
Hi cher im a little lost on how to continue with doing the non functional requirements . I have already done the chart expansion and reverting it back to normal. right now I wanna try make it such that when I click on the expand icon and a particular chart, it will focus on that chart and only refresh for that chart while all other charts will not refresh. I'm quite unclear about what the requirement means by pause. does it means it will stop fetching request or stop refreshing. whichever the case is, i am not really sure on how do i go about targeting a specific chart .

my idea was that inside auto-refresh.mjs i would do an if to check if there was a chart being expanded and if there was i would refresh only that chart every 3 seconds . else i would perform the normal auto refresh which is to refresh all charts for the same rate. the problem with this is im not really sure how i can go about checking if a chart has been expanded or not since the method i used to expand my chart was done in index.html . i was thinking of placing a value whenever i expanded a chart and using that value as a way to use an if check (e.g. when i expand error chart assign value of lets say 1 and ltr in refresh-chart.mjs do  if charts == 1 refresh error chart)

my problems are :  
1. not sure if im on the right track with that concept
2. unsure how to go about getting this value into refresh-chart.mjs (assuming im even suppose to do that)
    - not sure if i can export functions in a html script ( tried but failed )

**Comment by jeremiah-ang** [comment]
Replied in MS Teams
